### ISSUE TITLE
need explanation 

### ISSUE THREAD

**Issue by mayurvpatil** [ghoneycutt/serverspec_demo#1]
I'm noob and learning Serverspec, I'm trying for hour  to run server spec against EC2 instance with public ip , port ( 22 mostly ) and private key. 

could any one update readme.md for this ?

**Comment by ghoneycutt** [comment]
@mayurvpatil This repo is old and serverspec isn't really maintained. Suggest using Chef's InSpec.

https://docs.chef.io/inspec/
